Repository mohanadarafe/s341-witwit, pull requests merged in 2019-03, with the labels that each got.

#180 Travis CI Testing Template
  .travis.yml
  tests.js
Labels: High

#243 Update Back-End Edit Profile + Implementation Back-End Reset Password
  server/routes/main_pages/profile.js
  src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.html
  src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.ts
  src/app/profile/dialogs/password-dialog/password-dialog.component.html
  src/app/profile/dialogs/password-dialog/password-dialog.component.ts
  src/app/profile/pages/user-info-card/user-info-card.component.ts
  src/app/profile/services/profile.service.ts
Labels: back end

#273 Refactoring
  server/routes/followUsers.test.js
Labels: Refactoring
